routes:
  /:
    data: page.home
    template: home

collections:
  /portfolio/:
    permalink: /portfolio/{slug}/
    template: portfolio
    filter: tag:[hash-portfolio]
  /collection/:
    permalink: /collection/{slug}/
    template: collection
    filter: tag:[hash-collection]
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: tag:[hash-blog]
  /film-stock-archive/:
    permalink: /film-stock-archive/{slug}/
    template: index
    filter: tag:[hash-film-stock-archive]

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
